# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SceneKitDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SceneKitDemo

  target 'SceneKitDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SceneKitDemoUITests' do
    # Pods for testing
  end
pod 'SwiftMessages'

end
